### ISSUE TITLE
New get aliases

### ISSUE THREAD

**Issue by roman-dubrovsky** [datarockets/dotfiles#19]
Add aliases for `gci -m` and `gco master`

**Comment by MProG** [comment]
@roman-dubrovsky Alias for alias... I think this not good. And gci  != gco

**Comment by AleksSenkou** [comment]
@roman-dubrovsky I'd not add it too. Too deep nesting. What do you think?

**Comment by roman-dubrovsky** [comment]
@AleksSenkou 😡 as you want. This will be my personal aliases

**Comment by AleksSenkou** [comment]
@roman-dubrovsky ok, how would you name them?

**Comment by dzhlobo** [comment]
Using `gci -m` is bad practice. You should write good commit messages ;).

**Comment by ezhlobo** [comment]
@Proghat could you describe what is a good commit message? Do you mean that we always should write commit body?

**Comment by dzhlobo** [comment]
@ezhlobo, when you always open an editor for commit message it encourages you to think about the body. You may add a link to the task body. You may quickly describe why you did changes in this particular commit. But when you do `gci -m` you have no opportunity to stop and think about the commit description.

**Comment by ezhlobo** [comment]
@Proghat interesting point, turned off `gcim` and will check how it works
