### ISSUE TITLE
Add Wiki page with steps for installing dot files on Ubuntu

### ISSUE THREAD

**Issue by roman-dubrovsky** [datarockets/dotfiles#21]
this'll be useful  if we are going to suggest this configs to students from datarockets school

@Proghat @ezhlobo what do you think?

**Comment by ezhlobo** [comment]
@roman-dubrovsky good idea but I would prefer README instead of Wiki.

**Comment by dzhlobo** [comment]
@roman-dubrovsky, I'd like to see it in readme as well.

**Comment by roman-dubrovsky** [comment]
@ezhlobo @Proghat sure? Almost all our guys are using MacBooks and I don't see any reason for making README bigger for somebody else. 

I prefer to do instructions for ubuntu as wiki page and add this link in README. Does it work for you?

**Comment by ezhlobo** [comment]
@roman-dubrovsky how big the difference between installing on osx and ubuntu? 

I guess the only difference is in installing [rcm](https://github.com/thoughtbot/rcm) and everything else is going to be the same.

So we can describe how to install rcm on osx and ubuntu just in our readme. And leave link to original repository to cover more operating systems.

What do you think?

//CC @Proghat

**Comment by dzhlobo** [comment]
Let's add it to the README for now so we have single source of information. I often install dotfiles on servers and also in vagrant so it's pretty popular case.

**Comment by DDKatch** [comment]
@dzhlobo why not just implement a bash/ruby or whatever language script which will do all the necessary things?
I usually clone my dotfiles repo and run a rake task inside of it. Yes, [my current tasks](https://github.com/DDKatch/dotfiles/blob/master/Rakefile) are kind of outdated, but they helped me a lot in their prime.

**Comment by dzhlobo** [comment]
@DDKatch, yes, I think it would be great to have an automatic installation script 👍. Thank you for sharing. We probably should do this task after #33.
