### ISSUE TITLE
Simplify onboarding for iterm users

### ISSUE THREAD

**Issue by ezhlobo** [datarockets/dotfiles#24]
Iterm is widely used, I guess that it's worth to make our guide help set the iterm up. It will require just to set this option though:

<img width="1128" alt="2019-01-19 10-22-53" src="https://user-images.githubusercontent.com/974552/51423673-892daf00-1bd4-11e9-8bfe-c3ae76980f77.png">

**Comment by dzhlobo** [comment]
I would check if we somehow can make it configurable during installation. If we cannot I would at least add this information the README.

**Comment by paydaylight** [comment]
@dzhlobo not quite sure whether we should mix it into readme. Should we rather add a guides section in the wiki maybe?
