### ISSUE TITLE
Make prompt configurable

### ISSUE THREAD

**Issue by dzhlobo** [datarockets/dotfiles#27]
I want to make prompt configurable to make it easier to install dotfiles on servers. It is necessary to include host in prompt on server. 

Right now the only way to do this is to redefine PS1 in `.zsh.local` which is not optimal because in that case we will execute setting PS1 twice.

**Comment by dzhlobo** [comment]
I don't know how to check whether we're on the server or local machine automatically. I think we might want to check an env variable `PROMPT_HOSTNAME_COLOR` and if it's set then we add the hostname to the prompt.

On server or whatever machine we want (like vagrant) we may want to define this var in `.zsh.local` so a colored hostname is shown in the prompt.

**Comment by paydaylight** [comment]
@dzhlobo what is generally used for remote server connection in datarockets, SSH? If so SSH_TTY, SSH_CLIENT, SSH_CONNECTION env variables are defined when connecting via ssh

**Comment by dzhlobo** [comment]
Yes, ssh. That's great idea @paydaylight, I love it ❤️, I think that's exactly what I was dreaming for!

**Comment by dzhlobo** [comment]
I'm thinking if we also can get a hash from a hostname and map it to a color so we can paint a hostname with distinguished color. But I think it's probably should be a separate issue.

**Comment by paydaylight** [comment]
@dzhlobo The first answer from [here](https://superuser.com/questions/1123671/hash-hostname-into-a-color ) actually does so, but I lack bash programming skills to understand the solution. I've checked it and it worked for me
