### ISSUE TITLE
Change git aliases to push to either "main" or "master" brach, whatever is available

### ISSUE THREAD

**Issue by dzhlobo** [datarockets/dotfiles#30]
Many repositories are switching "master" branch to "main". I want to be able to use "gpom" alias with "main" branch as well.

I think we might want to use a function instead of alias which would check what branch is available to push to the correct one.

**Comment by paydaylight** [comment]
@dzhlobo wouldn't it be easier to push to whatever HEAD refers to?

**Comment by dzhlobo** [comment]
Yes, I think it would do the job 👍.

It's great to learn something, I just never use `git push origin HEAD` in my entire career :).

**Comment by paydaylight** [comment]
closing this issue, merged pull request #34
