### ISSUE TITLE
Setup softwrap for markdown files via editorconfig

### ISSUE THREAD

**Issue by dzhlobo** [datarockets/dotfiles#31]
I hope it's possible to do via editorconfig.

**Comment by paydaylight** [comment]
@dzhlobo EditorConfig does not support soft wraps, but this can still be achieved by tweaking settings in a text editor.
Vscode example:
```json
{
    "[markdown]": {
        "editor.wordWrap": "wordWrapColumn",
        "editor.wordWrapColumn": 80
    }
}
```

**Comment by dzhlobo** [comment]
@paydaylight, got it 👍. Yeah, I configured it in my vscode but was wondering if we can push it for everyone. Thank you for checking, I'm closing this issue for now than.
