### ISSUE TITLE
Common shortcuts for tmux

### ISSUE THREAD

**Issue by chyrta** [datarockets/dotfiles#4]
I would like to use tmux, but default shortcuts are kinda hard to use. May some of us who use it could share config or write a simple description for setting it up?

**Comment by dzhlobo** [comment]
@chyrta, see my config with comments in #7: https://github.com/datarockets/.dotfiles/blob/tmux/tmux.conf

**Comment by chyrta** [comment]
Thank you so much.

**Comment by dzhlobo** [comment]
It's in master now: https://github.com/datarockets/dotfiles/blob/master/tmux.conf.
