### ISSUE TITLE
Rename repository to "dotfiles"

### ISSUE THREAD

**Issue by dzhlobo** [datarockets/dotfiles#5]
I see that "dotfiles" is pretty common name. Compare with ".dotfiles": https://github.com/search?utf8=%E2%9C%93&q=.dotfiles&type=Repositories&ref=searchresults

What do you think about ".dotfiles" vs. "dotfiles"

**Comment by evgenTraytyak** [comment]
:+1:

**Comment by dzhlobo** [comment]
Cool!
